apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus-app
  template:
    metadata:
      labels:
        app: quarkus-app
    spec:
      containers:
        - name: quarkus-app
          image: docker.io/emsitpro/ems-api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"  # sesuaikan dengan service Kafka di cluster
