apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
  namespace: default
spec:
  selector:
    app: quarkus-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
